Previously, calling it caused program abort.

Thanks for fixing @mlin !

