Hi,

In my junit test case, I repeatedly write to rocks db, close it (by closing all rocks resource I can think of, then `RocksDB.close()`), delete the db, and start over again. At random time I would get this error:

```
Assertion failed: (refs_.load(std::memory_order_relaxed) == 0), function ~ColumnFamilyData, file db/column_family.cc, line 412.
```

This error appears on random time of the test, always after the delete db. I suspect the `RocksDB.close()` is not completed yet in the background when the db is deleted in disk. Is this possible?

In my test I use only default column family, so there is no need to close the column family explicitly. Is this correct?

Thanks,
Sam

